### ISSUE TITLE
Have the fast-charge problem been solved？ 

### ISSUE THREAD

**Issue by Xianbei233** [stockmind/gpd-pocket-ubuntu-respin#3] opened 2017-07-02 14:33 UTC
I have install the ISO you respined , but the fast charge seems not work when i use with charge. The battery use the power slowly.

**Comment by stockmind** [comment] 2017-07-02 15:17
You should try to install latest kernel.

You can download updated kernel for better charge management and other
stability fixes:
https://drive.google.com/uc?export=download&id=0B8-M0eiR7v8sRkZPOGxiUXpHMjQ

Extract in a folder then run "sudo dpkg -i *.deb"

Il 02 lug 2017 16:33, "先辈" <notifications@github.com> ha scritto:

**Comment by Xianbei233** [comment] 2017-07-02 15:25
Thanks，i will try. And there is another problem. The Scaling I set can not be saved after reboot. Do I need to change the system files?And which file is it?

**Comment by stockmind** [comment] 2017-07-02 15:58
You can change dpi setting into /etc/Xsession.d/90x11-rotate_and_scale to
reflect your dpi preference.

It will set the setting on boot.

Il 02 lug 2017 17:25, "先辈" <notifications@github.com> ha scritto:

**Comment by Xianbei233** [comment] 2017-07-03 06:27
Nice Work！Thank you very much. Problems are almost sovled. But there is new problem that I charge the machine by hot plug and the screen will suddenly sleep or maybe shutdow. Is this a normal phenomenon?

**Comment by scofieldpeng** [comment] 2017-07-04 18:07
@Xianbei233 hello, i install the kernel but the fast charging still not work, how about u? my kernel version now is: 4.12.0-rc7-custom #1 SMP Wed Jun 28 11:08:24 BST 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by stockmind** [comment] 2017-07-17 13:51
Hans is working on it. It's related to the USB Type C port management that's still a work in progress. He know what to do, it's just a matter of some weeks to get it working correctly!

**Comment by cawilliamson** [comment] 2017-07-28 21:14
It's ballocks all this fast charging crap.

The device fast charges if you have the correct charger. It's a PD 2.0 (Power Delivery 2.0) spec charger that you need - if you're using some Qualcomm QC crap - it wont work.

Buy yourself a decent charger, buy yourself a decent USB-C cable. It fast charges just fine. Not sure why people are flipping out about this.

**Comment by snazzybunny** [comment] 2017-07-28 21:57
Do you have a charger recommendation?

**Comment by cawilliamson** [comment] 2017-07-28 22:00
Really depends where you live - for me (UK):

https://www.amazon.co.uk/gp/product/B01MYVJELP/ref=oh_aui_detailpage_o07_s00?ie=UTF8&psc=1

**Comment by scofieldpeng** [comment] 2017-07-29 04:56
i fact i use the charger the GPD Pocket give to me, and the charger support the PD2.0 but the fast charger still not work

**Comment by cawilliamson** [comment] 2017-07-29 08:36
@stockmind - what kernel build are you using here? I've had fast charging working for weeks and weeks at this point.

**Comment by huangtao00** [comment] 2017-07-29 08:43
@cawilliamson really? we have been waiting for a long time. what version of kernel do u use right now? my kernel version is 4.12.0-rc7-custom

> meyou@meyou-Default-string:~$ uname -r
> 4.12.0-rc7-custom

**Comment by stockmind** [comment] 2017-07-29 12:52
I'm using your compiled rc7 and latest Hans compiled kernel. As i pointed out on Reddit (https://www.reddit.com/r/GPDPocket/comments/6idnia/linux_on_gpd_pocket/djtpyi1/) charging for me works only in a way that doesn't drain battery but also doesn't charge it. You can use for hours and have same percent of battery in use.

I have asked this to Hans and got this reply: 
"This is related to the USB-C connector not yet being fully supported, part of the
work that needs to be done is ensure that different charger types are identified
correctly."

That, for what i can understand, is the work that Hans is committing in the latest days.
(As the second USB C battery charger icon show)

**Comment by cawilliamson** [comment] 2017-07-29 13:51
That's very odd - I haven't had that problem for a long time.

Ever since I first installed the kernel from Hans I have been able to charge AND use my device at the same time. I did have a chat with Hans about it at one point and I ended up buying a USB-C adapter which displays the charging rate. Turns out I was using a QC2.0 charger instead of DP2.0 charger but once I got the DP one I've had zero issues charging it at all.

I know there are problems with USB-C *data* but not power (i.e. charging.)

I'm really not sure what to say other than that I can confirm with 100% certainty that I am able to both charge and use my GPD Pocket at the same time under both Ubuntu 16.04 and ArchLinux using the last kernel sources I had.

Perhaps try building a kernel from the hans repo using the next-drm branch and see how it goes. That branch is enough commits behind that it doesn't contain any of the breaking changes in the newer commits.

**Comment by stockmind** [comment] 2017-07-29 13:59
The charger that you get with GPD Pocket is a QC2.0 or DP2.0?
With the stock charger you can charge up at full speed?
I've buyed an Anker one as you pointed out on Amazon and will try with that!

**Comment by cawilliamson** [comment] 2017-07-29 14:26
I've never tried the original charger - doesn't fit the UK plug sockets.

Though the one you get with the pocket is DP2.0 and the one you need is
indeed DP2.0 so it should work

**Comment by stockmind** [comment] 2017-07-29 14:58
I'll buy a tester also to check and see if we can find out where the problem is.
Could be a different charger quality? Maybe yours have some sort of circuit fallback to handle correct charge, GPD doesn't seems to have shipped the best quality accessories. I'm just speculating.
Also if you don't mind could you please share the exact kernel you're using? 
During install of kernel you're also encountering the warning about possible missing firmwares of i915?
We can try to isolate the problem.

**Comment by kanocz** [comment] 2017-07-29 17:58
what about versions of BIOS? this also may affect

**Comment by stockmind** [comment] 2017-07-31 19:24
Anker charger arrived and i can confim that fast charging works. Battery gets charged while system is in use. Kernel 4.12-RC7. BIOS updated.
Stock charger instead keep just battery charge stable.
I can notice also that with Anker charger system inform of 1.30h for complete charge on 66% of battery.
GPD stock charger when connected raise this value to 14h for a complete charge. Stock charger lead to strange behaviour also on Unity when charger gets plugged in, system go to suspend/sleep.
The Anker one doesn't trigger instead this behavior.
There must be some problems recognizing the GPD stock charger and its capabilities.
I'm waiting for my usb c tester to study in deep this.

**Comment by snazzybunny** [comment] 2017-07-31 19:26
Got a link to the anker charger? Thanks.

**Comment by stockmind** [comment] 2017-07-31 19:37
cawilliamson one - https://www.amazon.co.uk/gp/product/B01MYVJELP/ref=oh_aui_detailpage_o07_s00?ie=UTF8&psc=1
mine - https://www.amazon.it/gp/product/B01N6536VP/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1
Same model, just different country.

**Comment by kanocz** [comment] 2017-07-31 22:05
tested now with charger from Apple MacBook Pro 2017.... doesn't charge, just keeps stable :-(
just ordered https://www.amazon.de/dp/B071NPLFLJ/ref=pe_3044161_185740101_TE_item and https://www.amazon.de/dp/B01LXZP6RR/ref=pe_3044161_185740101_TE_item - will report when arrived

**Comment by cawilliamson** [comment] 2017-07-31 22:08
There is no reason at all that the Macbook charger would suddenly charge the GPD Pocket at full speed.

Apple products don't automatically support every possible charging technology on planet Earth! ;) You need a DP 2.0 charger (which is what I purchased.) I wasn't aware that the GPD charger was quite so "quirky" though - I just bought my charger because I can't stand using those crappy US -> UK adapters - they look (and work) like complete garbage.

Very glad I did purchase that charger now!

**Comment by stockmind** [comment] 2017-08-01 00:50
My GPD stock charger also have the adapter attached, the one that was in GPD box.. It's really cheap and don't really hold properly in the power socket, so this may not help.
Windows charges good anyway, but who knows!

**Comment by shepelt** [comment] 2017-08-01 08:02
I'm curious about what kind of USB c cables did you guys use to get the result?
Seems like USB c cables can affect the charging behavior as well.

**Comment by stockmind** [comment] 2017-08-01 08:04
I've made my tests using One cable from anker and the stock One. Same
result with both cables on the two different charter.

Il 01 ago 2017 10:02, "shepelt" <notifications@github.com> ha scritto:

**Comment by kanocz** [comment] 2017-08-01 09:54
@cawilliamson I know, just tested and posted info there for other peoples :) probably we need to create some list of compatible and not compatible chargers, because it's common issue that you'll see only "super fast charging" on charger without any specification of which technology is supported

**Comment by kanocz** [comment] 2017-08-03 17:25
charging works with charger from Samsung phone - about 4 hours from 5% to 100% with turned on gpd pocket on `4.12.0-rc7-custom` kernel

**Comment by cawilliamson** [comment] 2017-08-03 18:08
@kanocz No worries man - apologies for my snippy response - clearly I needed my morning coffee when I wrote that!! :(

**Comment by scofieldpeng** [comment] 2017-08-04 03:01
@kanocz hello, what's the spec about the samsung charger? 5v2a or 19v?

**Comment by huangtao00** [comment] 2017-08-04 03:37
I have tested the ubuntu 16.04 version given by gpd company,  the good thing is that they have added the fast charge supporting. just using the stock charger is ok and works.  but the bad thing is that the kernel they use is 4.12-rc2 and really very unstable.

**Comment by shepelt** [comment] 2017-08-04 06:21
@huangtao00  how did you get hold of the ubuntu image? last time I checked the one GPD posted on indiegogo was broken... (https://mega.nz/#!EQwUHTCC!3Qsf8UQxbAKiHzFSxwxVVjaw7Bq_boeo6Bk8IF5nZ7U)

**Comment by kanocz** [comment] 2017-08-04 06:26
@scofieldpeng it's "Adaptive Fast Charging" with regular USB connector (and usb -> usb-c cable), output 5v2a / 9v1.67a

**Comment by huangtao00** [comment] 2017-08-04 06:30
@shepelt try this link http://pan.baidu.com/wap/link?surl=1ge3CTiV&errno=0&errmsg=Auth%20Login%20Sucess&&bduss=&ssnerror=0#list/path=%2F&page=1

_Sent from my Asus ASUS_Z00A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by stockmind** [comment] 2017-08-07 01:58
Charger tests:
Stock GPD charger on **4.12-rc7 kernel** - 4.89v - **0.5a**
Anker charger on **4.12-rc7 kernel** - 4.89v - **2a**

Stock GPD charger on **4.12-rc2+ kernel (GPD official firmware)** - 4.70v - **2.5a**
Anker charger on **4.12-rc2+ kernel (GPD official firmware)** - 4.70v - **2.5a**

Great tips haungtao00! ISO from chinese link is good.
USB-C data still not working on their kernel.

@cawilliamson and other users, i'm uploading the working ISO on MEGA if you have problems downloading it from the chinese provider. It took me a little to successfully complete the download.

**Comment by stockmind** [comment] 2017-08-07 02:26
Official working GPD Ubuntu beta firmware
https://mega.nz/#!ZaoCDSqA!tbFx0Pev2dU0al8iVdmvNNiEA9RuL2jLZQV9md1S-iI

**Comment by kanocz** [comment] 2017-08-07 06:53
@stockmind can you please do charger tests on Windows? it looks like with Linux we're not using PD2.0 at all but only 5V mode :-(

**Comment by stockmind** [comment] 2017-08-07 18:44
Sure!
Stock GPD charger - **Windows** - 11.70v - **1.7a**
Anker charger - **Windows** - 8.90v - **2a**

**Comment by stockmind** [comment] 2017-08-07 18:51
Latest kernel build from Hans repo:
Stock GPD charger - **4.13-rc3** - 11.8v - **1.5a**
Anker charger - **4.13-rc3** - 9.20v - **0.5a**

**Comment by huangtao00** [comment] 2017-08-07 22:57
@stockmind wonderful!! thx for your testing. could u please give us the latest kernel from Hans repo!

_Sent from my Asus ASUS_Z00A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by stockmind** [comment] 2017-08-08 02:02
Kernel files:
EDIT: https://drive.google.com/open?id=0B8-M0eiR7v8sTlJMU01DMm1ZOW8

On this kernel i still get the frequencies problem. 
Cpu is fixed at 1600MHz so this will drain battery faster.

**Comment by huangtao00** [comment] 2017-08-08 02:40
@stockmind the link u gave is not available now . could u please send it again?

_Sent from my Asus ASUS_Z00A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by stockmind** [comment] 2017-08-08 03:00
Ops! EDIT: https://drive.google.com/open?id=0B8-M0eiR7v8sTlJMU01DMm1ZOW8

**Comment by kanocz** [comment] 2017-08-08 06:25
in `4.13-rc4` is fixed intel pstate (https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/diff/drivers/cpufreq/intel_pstate.c?id=v4.13-rc4&id2=v4.13-rc3) so probably this will help

**Comment by stockmind** [comment] 2017-08-08 13:04
Thanks! Those fixes seems already merged into Hans repository but i continue to see frequencies fixed at 1600 MHz. Do you get same results on your machine?

    cat /proc/cpuinfo | grep MHz

**Comment by stockmind** [comment] 2017-08-08 22:54
Frequencies works as expected. Value there is not just updated or work like in older kernels atm.

**Comment by huangtao00** [comment] 2017-08-09 09:20
@stockmind what did u mean "as   expected"

_Sent from my Asus ASUS_Z00A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by huangtao00** [comment] 2017-08-09 09:20
@stockmind what did u mean "as   expected"

_Sent from my Asus ASUS_Z00A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by stockmind** [comment] 2017-08-09 10:00
*I've deleted duplicate comment*
It's working correctly, sorry. So it's ok to use that kernel! :)
I'm in talk with Hans and i will try a patch he wrote to see if is possible to fix the two battery thing. 
Will update when we succeed!

**Comment by huangtao00** [comment] 2017-08-09 10:10
@stockmind thx, waiting for your message on the patched kernel 

_Sent from my Asus ASUS_Z00A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by scofieldpeng** [comment] 2017-08-11 05:42
update, the gpd pocket company release the 2nd beta iso, chinese download link: [https://pan.baidu.com/s/1jIBV13K](https://pan.baidu.com/s/1jIBV13K)

**Comment by stockmind** [comment] 2017-08-11 06:06
I'm downloading it right now. It will take awhile... 9h at 70kbs

**Comment by stockmind** [comment] 2017-08-12 05:30
Didn't installed new GPD firmware yet but in the meanwhile Hans as fixed the two battery thing and charging with Aukey charger!! :)

Here is a kernel to test:
https://drive.google.com/open?id=0B8-M0eiR7v8sZFZVTExQb2NoWTg

Will compile a new one with a better name, in the meanwhile test it out! :)
Charging with Aukey charger here is really fast! 1.9a to 2.4a while charging.

**Comment by scofieldpeng** [comment] 2017-08-13 14:59
@stockmind wow, good news, how about the Stock charger? can use the fast charge?

**Comment by petrmatula190** [comment] 2017-08-15 09:32
@scofieldpeng:
I get my repaired Pocket on yesterday, so I can start testing. I make ubuntu 16.04.2 installer witch custom battery kernel from https://drive.google.com/open?id=0B8-M0eiR7v8sZFZVTExQb2NoWTg
I have some system freezes after install, but after manual update grub and fan systemd service, all is OK and very usable.
I use only stock charh¨get and It is working perfect. I need some more test witch all my PPAs, but charging speed witch youtube in firefox and brigithless 100% is around 3-4%/5minutes. It is perfect.

**Closed as completed** 2017-08-27 06:35 UTC
